### ISSUE TITLE
Enquiry into Objectives calculation for saving best model

### ISSUE THREAD

**Issue by mckhang** [pfnet-research/meta-tasnet#10]
Hi, thanks for your great work. 
Just one point of enquiry in objectives calculation prior to saving the best validation model in train.py

I am specifically referring to the following:
objective = average_stats[-5:-1].mean()

I would like to ask why the slicing is [-5:-1] instead of [-4:] ?

Hope to seek your clarification and thanks in advance!

**Comment by davda54** [comment]
Hi, thank you for finding this bug! I believe you're right, but changing it shouldn't make any significant difference :)
